package ankit

import (
	"encoding/csv"
	"io"

	"github.com/pkg/errors"
)

// Note consists of fields.
type Note interface {
	Fields() []string
}

// Deck is a group of cards, which are generated by notes.
type Deck interface {
	Notes() ([]Note, error)
}

// WriteToCSV write deck's notes to io.Writer.
func WriteToCSV(d Deck, w io.Writer) error {
	cw := csv.NewWriter(w)

	notes, err := d.Notes()
	if err != nil {
		return errors.Wrap(err, "cannot get notes from deck")
	}

	for _, note := range notes {
		fields := note.Fields()
		if err := cw.Write(fields); err != nil {
			return errors.Wrap(err, "cannot write field to csv")
		}
	}
	cw.Flush()

	return nil
}
