package ankit

import (
	"encoding/csv"
	"io"
	"log"

	"github.com/pkg/errors"
)

// Note consists of fields.
type Note interface {
	Err() error
	Fields() []string
}

// Deck is a group of cards, which are generated by notes.
type Deck interface {
	Note(keys ...interface{}) <-chan Note
	Notes() <-chan Note
}

// Export write Deck's notes to io.Writer.
func Export(w io.Writer, d Deck, keys ...interface{}) error {
	cw := csv.NewWriter(w)

	var notes <-chan Note
	if len(keys) == 0 {
		notes = d.Notes()
	} else {
		notes = d.Note(keys...)
	}

	for note := range notes {
		if err := note.Err(); err != nil {
			log.Printf("note error: %v", err)
			continue
		}

		fields := note.Fields()
		if err := cw.Write(fields); err != nil {
			return errors.Wrapf(err, "cannot write fields %v to csv", fields)
		}
	}
	cw.Flush()

	return nil
}
